### ISSUE TITLE
Hello Todd and Nic. Can you please sort this out? I have the bucket in place and dont get a container connect?

### ISSUE THREAD

**Issue by mmaedel** [couchbaselabs/comply#1]
$ npm install couchbase
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> couchbase@2.1.4 install C:\Users\mädel\home\comply\node_modules\couchbase
> prebuild --install

prebuild WARN install Prebuilt binaries for node version v5.7.1 are not available
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at failNoPython (C:\Users\mädel\home\comply\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! stack     at C:\Users\mädel\home\comply\node_modules\node-gyp\lib\configure.js:356:11
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at failNoPython (C:\Users\mädel\home\comply\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! build     at C:\Users\mädel\home\comply\node_modules\node-gyp\lib\configure.js:356:11
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN cean-stack-webinar@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mädel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "couchbase"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! couchbase@2.1.4 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the couchbase@2.1.4 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the couchbase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs couchbase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls couchbase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mädel\home\comply\npm-debug.log

[npm-debug.txt](https://github.com/couchbaselabs/comply/files/169500/npm-debug.txt)

WHAT DO NEXT? Thank you

Matthias

**Comment by avsej** [comment]
@mmaedel does this help? http://stackoverflow.com/a/35452611/98509

**Comment by mmaedel** [comment]
@avsej , thanks for support :) but unfortunatly still difficulties in getting it up :(

like:

mädel@schnee ~/comply
$ node app.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'couchbase'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\mädel\home\comply\app.js:3:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by mmaedel** [comment]
ok it seems really complicated on windows... :(
like:

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows
https://github.com/felixrieseberg/npm-windows-upgrade
https://github.com/Microsoft/nodejs-guidelines/blob/master/getting-started.md#managing-npm-dependencies

nearly ging up ...:(
